bazel_dep(name = "rules_oci", version = "2.2.2")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "nginx_image",
    digest = "sha256:db3099a8d62d2bd8f5f7875e6e3d2dfbd92c999cd35967fb05d41374386535e1",
    image = "index.docker.io/library/nginx",
    platforms = ["linux/amd64"],
    tag = "1.31.5",
)
